name: "Twilio-Whatsapp Action"
description: "Recieve repo notifications on your whatsapp when a push occurs in the master branch"
author: "mdb571"
branding:
  icon: message-square
  color: black

inputs:
  from:
    description: "The twilio whatsapp number from which the sms should be sent"
    required: true
  to:
    description: "The number which is configured with twilio"
    required: true
  twilio_account_sid:
    description: "Twilio Accout SID from twilio console"
    required: true
  twilio_auth:
    description: "Twilio Authentication token from console"
    required: true
  message:
    description: "Message to send"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"